print(" 2- Dar un string <nombre> y despliegue un saludo ¡hola <nombre>!.")
print(" ")#define una linea en blanco
print(" Roman De la Cruz Leonardo antonio,(2),1211,3-w")
print(" ")#define una linea en blanco
print(" ")#define una linea en blanco
#SOLICITA EL NOMBRE AL USUSARIO
nombre = str(input("Ingresa tu nombre: "))
print(" ")#define una linea en blanco
#DEFINE
def saludar(nombre):
#IMPRIME EL MENSAJE CON EL NOMBRE
    print("mucho gusto",nombre)
print(" ")#define una linea en blanco
# Llamar a la función con un nombre
print("mucho gusto", nombre)